### ISSUE TITLE
analog_input

### ISSUE THREAD

**Issue by linus8533** [Nilon123456789/firmetix#4]
I made a simple circuit with a potentiometer and used example analog_input.py to read the value. After I stop turning the potentiometer, the output continues for seconds.
The same program seems to work much faster with telemetrix.

How can this be solved?

**Comment by Nilon123456789** [comment]
The issued should be fixed in the latest release [v7.0.2](https://github.com/Nilon123456789/firmetix/releases/tag/v7.0.2) with the commit d0198253fac14665c2527209e1b29221d41f8292

If the issue persists please reopen the issue

**Comment by linus8533** [comment]
I see no difference after installing v7.0.2. The output is still lagging.
