### ISSUE TITLE
RuntimeError: Incorrect Arduino ID

### ISSUE THREAD

**Issue by linus8533** [Nilon123456789/firmetix#8]
Hello 
After updating python_firmetix tot version 7.1.0 and on de arduino to 7.1.1 I get a runtime - error:

….\AppData\Local\Programs\Python\Python311\Lib\site-packages\firmetix\firmetix.py", line 332, in __init__
    self._find_arduino()
  …..\Python\Python311\Lib\site-packages\firmetix\firmetix.py", line 503, in _find_arduino      
    raise RuntimeError(f'Incorrect Arduino ID: {self.reported_arduino_id}')
RuntimeError: Incorrect Arduino ID: []

I hope you can fix this.

**Comment by Nilon123456789** [comment]
Which version did you use on the arduino? And what is your arduino model?

**Comment by linus8533** [comment]
I ‘m using an arduino UNO. On the uno firmetix version 7.1.2 and on the desktop 7.1.1.

 

Van: Nilon123456789 ***@***.***> 
Verzonden: zondag 27 augustus 2023 19:00
Aan: Nilon123456789/firmetix ***@***.***>
CC: linus8533 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nilon123456789/firmetix] RuntimeError: Incorrect Arduino ID (Issue #8)

 

Which version did you use on the arduino? And what is your arduino model?

**Comment by Nilon123456789** [comment]
Did did you check that you have the same id set in your arduino script and in python? (Default one is 1)

**Comment by linus8533** [comment]
I didn’t make any changes. So far as I can see both are set to 1.

 

Van: Nilon123456789 ***@***.***> 
Verzonden: maandag 28 augustus 2023 12:09
Aan: Nilon123456789/firmetix ***@***.***>
CC: linus8533 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nilon123456789/firmetix] RuntimeError: Incorrect Arduino ID (Issue #8)

 

Did did you check that you have the same id set in your arduino script and in python? (Default one is 1)

**Comment by Nilon123456789** [comment]
Did you try running the example blink. And are you on Windows, Mac or Linux.

**Comment by linus8533** [comment]
I’m on windows and blink works ok. Furthermore telemetrix also works ok.

 

Van: Nilon123456789 ***@***.***> 
Verzonden: maandag 28 augustus 2023 20:06
Aan: Nilon123456789/firmetix ***@***.***>
CC: linus8533 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nilon123456789/firmetix] RuntimeError: Incorrect Arduino ID (Issue #8)

 

Did you try running the example blink. And are you on Windows, Mac or Linux.

**Comment by Nilon123456789** [comment]
Is the problem still going?

**Comment by linus8533** [comment]
Sorry, a misunderstanding. The arduino “blink” worked ok. The firmetix blink gives the same error message.

 

 

Van: Nilon123456789 ***@***.***> 
Verzonden: woensdag 30 augustus 2023 18:52
Aan: Nilon123456789/firmetix ***@***.***>
CC: linus8533 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nilon123456789/firmetix] RuntimeError: Incorrect Arduino ID (Issue #8)

 

Is the problem still going?

**Comment by Nilon123456789** [comment]
Try increasing the Arduino wait time when creating the board.

**Comment by linus8533** [comment]
That works for me. A value of 2 seconds seems to be enough. One second is too short.

 

 

 

Van: Nilon123456789 ***@***.***> 
Verzonden: dinsdag 12 september 2023 18:18
Aan: Nilon123456789/firmetix ***@***.***>
CC: linus8533 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nilon123456789/firmetix] RuntimeError: Incorrect Arduino ID (Issue #8)

 

Try increasing the Arduino wait time when creating the board.

**Comment by Nilon123456789** [comment]
Alright, I will then close the issue and publish a new version (7.1.2)
